// Each set of lines has a differnt MTA API endpoint
// Values are the end of the MTA urls for each line
export const feeds: { [key: string]: string} = {
  a: "-ace",
  c: "-ace",
  e: "-ace",
  ace: "-ace",
  b: "-bdfm",
  d: "-bdfm",
  f: "-bdfm",
  m: "-bdfm",
  bdfm: "-bdfm",
  g: "-g",
  j: "-jz",
  z: "-jz",
  jz: "-jz",
  n: "-nqrw",
  q: "-nqrw",
  r: "-nqrw",
  w: "-nqrw",
  nqrw: "-nqrw",
  l: "-l",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "",
  123: "",
  456: "",
  123456: "",
  7: "-7",
  sir: "-si",
  si: "-si",
};
